language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -e .
script:
  - python setup.py test
notifications:
  email:
    recipients:
      - jespinog@gmail.com
    on_success: change
    on_failure: change
